name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  react_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm install, run
        run: |
          cd frontend/pingwiny
          npm install
          npm run
